#!/bin/bash

CPATH=.
CPATH=$CPATH:lib/*
CPATH=$CPATH:build/classes

# To set the page-size to use, add "-Dnanodb.pagesize=2048" to JAVA_OPTS.
# To enable transaction processing, add "-Dnanodb.txns=on" to JAVA_OPTS.
JAVA_OPTS="-Dlog4j.configuration=logging.conf -Dnanodb.pagesize=512"

# See if we have the rlwrap utility; if so, it makes using NanoDB
# from the command-line sooo much nicer...
testrl=$(which rlwrap)
if [ -z "$testrl" ] 
then
    java $JAVA_OPTS -cp $CPATH edu.caltech.nanodb.client.ExclusiveClient
else
    rlwrap java $JAVA_OPTS -cp $CPATH edu.caltech.nanodb.client.ExclusiveClient
fi
